"""Update user model

Revision ID: 221171d88339
Revises: a63ac65502d4
Create Date: 2026-10-08 16:49:11.634247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221171d88339'
down_revision: Union[str, Sequence[str], None] = 'a63ac65502d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_name_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_name_key'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
