"""Update usermodel

Revision ID: a63ac65502d4
Revises: fa12d72487a8
Create Date: 2026-10-07 20:19:19.765235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63ac65502d4'
down_revision: Union[str, Sequence[str], None] = 'fa12d72487a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_hashed_password_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_hashed_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
