"""create month goal table

Revision ID: ae6a612f3b26
Revises: dfbae4f3e792
Create Date: 2026-10-01 21:14:07.059736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6a612f3b26'
down_revision: Union[str, Sequence[str], None] = 'dfbae4f3e792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthgoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('month', sa.Enum('SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='month'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthgoal')
    # ### end Alembic commands ###
