"""Solve problem with env in alembic directory

Revision ID: fa12d72487a8
Revises: 855af105152b
Create Date: 2026-10-02 14:56:38.080059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa12d72487a8'
down_revision: Union[str, Sequence[str], None] = '855af105152b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daygoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['monthgoal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daygoal')
    # ### end Alembic commands ###
